name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Create Global Config Overlay File
      run: |
        # Write the required CPU masks directly to a root overlay file that Kconfig cannot wipe
        echo 'CONFIG_LITTLE_CPU_MASK="0x3f"' > all.config
        echo 'CONFIG_BIG_CPU_MASK="0xc0"' >> all.config

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M dogi

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
        # This forces the build engine to merge the overlay settings during configuration
        KCONFIG_ALLCONFIG: all.config
      with:
        arch: arm64
        compiler: clang/11
        defconfig: violet_stock_defconfig
        image: Image.gz-dtb

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: module
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/dogi_memk.ko
